[app]
log_level = "debug" # `debug` for verbose logs. `info` otherwise.
env = "dev" # dev|prod.
refresh_interval = "10s" # Interval at which `index.json` gets stored in `data_dir`.
nomad_data_dir = "/opt/nomad/data/alloc" # Nomad data directory where allocs are stored.
vector_config_dir = "examples/vector/" # Path to the generated vector config file.
extra_templates_dir = "static/" # Extra templates that can be given. They will be rendered in `$vector_config_dir`. You can use variables mentioned in vector.tmpl if required.

[stream]
max_reconnect_attempts = 5 # Maximum reconnection attempts with Nomad Events API. After this limit is breached, program exits.
