
[sources.source_nomad_alloc_2cbf80ff-ef2a-e634-33ec-e097a6061001_proxy]
type = "file"
include = [ "/opt/nomad/data/alloc/2cbf80ff-ef2a-e634-33ec-e097a6061001/alloc/logs/*" ]
line_delimiter = "\n"
read_from = "beginning"

[transforms.transform_nomad_alloc_2cbf80ff-ef2a-e634-33ec-e097a6061001_proxy]
type = "remap"
inputs = ["source_nomad_alloc_2cbf80ff-ef2a-e634-33ec-e097a6061001_proxy"]
source = '''
# Store Nomad metadata.
.nomad_namespace = "default"
.nomad_node_name = "pop-os"
.nomad_job_name = "nginx"
.nomad_group_name = "nginx"
.nomad_task_name = "proxy"
.nomad_alloc_id = "2cbf80ff-ef2a-e634-33ec-e097a6061001"
'''
